# Generated by Django 5.2.6 on 2025-10-01 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='ProductImage/')),
                ('productDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
    ]
